### ISSUE TITLE
Intermittent Failure

### ISSUE THREAD

**Issue by jacobwoffenden** [jacobwoffenden/barnsley-bin-day#2]
Occasionally Puppeteer will throw an error
```
/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:337
            throw new Error('Execution context was destroyed, most likely because of a navigation.');
                  ^

Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:337:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext._ExecutionContext_evaluate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:284:[56](https://github.com/jacobwoffenden/barnsley-bin-day/actions/runs/3042798165/jobs/4901352239#step:2:57))
    at async ElementHandle.evaluateHandle (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:164:16)
    at async Object.internalHandler.queryOne (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:25:30)
    at async ElementHandle.$eval (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:883:31)
    at async run (/app/app.js:32:23)
```
https://github.com/jacobwoffenden/barnsley-bin-day/actions/runs/3042798165/jobs/4901352239

**Comment by jacobwoffenden** [comment]
https://github.com/jacobwoffenden/barnsley-bin-day/actions/runs/3367220742

**Comment by jacobwoffenden** [comment]
https://github.com/jacobwoffenden/barnsley-bin-day/actions/runs/3416808253/jobs/5687295115

**Comment by jacobwoffenden** [comment]
Python rewrite seems to have fixed this
